# Generated by Django 3.0.5 on 2020-06-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IND', 'India')], max_length=4)),
                ('state', models.CharField(choices=[('AP', 'Andhra Predesh'), ('TS', 'Telangana')], max_length=4)),
                ('address_line', models.TextField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IND', 'India')], max_length=4)),
                ('state', models.CharField(choices=[('AP', 'Andhra Predesh'), ('TS', 'Telangana')], max_length=4)),
                ('address_line', models.TextField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
            ],
        ),
    ]
