# Generated by Django 3.0.5 on 2020-06-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_baseaddress_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivaryboy',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.BaseAddress'),
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.BaseAddress'),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.BaseAddress'),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.BaseAddress'),
        ),
    ]
