# Generated by Django 3.0.5 on 2020-07-02 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_address',
            name='zipcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
