# Generated by Django 3.0.5 on 2020-07-06 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Username!', message='Invalid Username!', regex='^[a-zA-Z][a-zA-Z0-9]{3,}')])),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invlaid Phone Number!', message='Invalid Phone Number!', regex='^[6-9][0-9]{9}$')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_country', models.CharField(choices=[('IND', 'India')], max_length=4)),
                ('owner_state', models.CharField(choices=[('AP', 'Andhra Predesh'), ('TS', 'Telangana')], max_length=4)),
                ('onwer_address_line', models.TextField(unique=True)),
                ('owner_city', models.CharField(max_length=30)),
                ('owner_landmark', models.CharField(max_length=30)),
                ('shop_country', models.CharField(choices=[('IND', 'India')], max_length=4)),
                ('shop_state', models.CharField(choices=[('AP', 'Andhra Predesh'), ('TS', 'Telangana')], max_length=4)),
                ('shop_address_line', models.TextField(unique=True)),
                ('shop_city', models.CharField(max_length=30)),
                ('shop_landmark', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=100, unique=True)),
                ('shop_image', models.ImageField(upload_to='shop_temp_images')),
                ('shop_description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
