# Generated by Django 3.0.5 on 2020-07-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200706_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Username!', message='Invalid Username!', regex='^[a-zA-Z][a-zA-Z0-9]{3,}')])),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invlaid Phone Number!', message='Invalid Phone Number!', regex='^[6-9][0-9]{9}$')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='delivery_boy_temp_images')),
                ('country', models.CharField(choices=[('IND', 'India')], max_length=4)),
                ('state', models.CharField(choices=[('AP', 'Andhra Predesh'), ('TS', 'Telangana')], max_length=4)),
                ('address_line', models.TextField(unique=True)),
                ('city', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='shoponline',
            name='owner_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shoponline',
            name='shop_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
