# Generated by Django 3.0.5 on 2020-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200706_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyjob',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoponline',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
